Improving CI
mdblp/blip pull request #1005
Opened 2022-12-13 14:58 UTC by fatb38

As we discussed together, a good practice is to name our docker images and github tags in lowercase. Improving CI in this way. For the moment, it still needs to comment the condition `if: github.ref_name == 'dblp'` in `build` and `publish` jobs to push a PR image. It will be improved soon ;)

2022-12-13 17:25 UTC, Nas84 requested changes

2022-12-13 17:25 UTC, Nas84 commented on .github/workflows/ci.yml
> +#    if: github.ref_name == 'dblp'
this publish steps is for dblp only

2022-12-13 17:25 UTC, Nas84 commented on .github/workflows/ci.yml
> +            type=ref,enable=true,prefix=${{ steps.package-version.outputs.semver }}-pr-,event=pr
to be removed

2022-12-13 17:25 UTC, Nas84 commented on .github/workflows/ci.yml
> +      - name: Creating new github tag
if enable should be based on the changelog to be common with all our repo

2022-12-14 16:05 UTC, yanngit commented
Already done by nasser https://github.com/mdblp/blip/pull/1008

2022-12-14 16:05 UTC, closed without merging