YLP-159 React 16 migration
mdblp/blip pull request #251
Opened 2020-09-10 13:14 UTC by franck-fourel

2020-09-17 08:37 UTC, Nas84 commented
require these PRs : 
 -  [Viz #69](https://github.com/mdblp/viz/pull/69)
- [Tideline #50](https://github.com/mdblp/tideline/pull/50)

2020-09-23 11:54 UTC, yvon-dblg requested changes
Looks good
- package-lock.json need to be regenerated
- Missing changelog

2020-09-23 11:54 UTC, yvon-dblg commented on package.json
> +    "create-react-class": "15.6.3",
Should be in dependencies, not dev

2020-09-23 11:54 UTC, yvon-dblg commented on package.json
> +    "@types/react": "^16.9.49",
Move it to devDependencies

2020-09-24 15:42 UTC, yvon-dblg approved these changes
LGTM

2020-09-24 15:52 UTC, merged