ylp-215 Display confidential mode
mdblp/blip pull request #315
Opened 2020-12-08 17:11 UTC by franck-fourel

Based on Zen mode branch (PR #313)
Below is an example of the display
![image](https://user-images.githubusercontent.com/22294614/101516935-65b6ad80-3980-11eb-85dd-1d097cd51f5c.png)

todos: 
- review tooltip so that it's centered on the lock of the main blocks
- add tests
- and probably more ...

2020-12-09 09:20 UTC, yvon-dblg reviewed
Missing translation in locales/en/translation.json

2020-12-09 14:59 UTC, yvon-dblg reviewed
- Since d3 & React are incompatible, I would have get the image from https://material.io/resources/icons/?icon=lock&style=outline (see example patch)
- Remove duplicate icons, put them in ./branding
- Simplify the tideline code to display then confidential mode (zen mode same problem, will be a plus)
- Tooltip incomplete
- Need to cleanup a little the code (test codes in comments...)

2020-12-14 08:24 UTC, franck-fourel commented
As we may expect events that can be much longer than usual events, here is the strategy that has been implemented to display the ToolTip for those types of events:
- up to 3 hours event: a standard tooltip is displayed with the lock icon and the message. No title. No Hours displayed. 
![image](https://user-images.githubusercontent.com/22294614/102057344-10e6bd00-3dee-11eb-80c3-8c05dde16934.png)
- more than 3 hours. No tooltip displayed. The lock icon and the 'Confidential Mode' message is displayed within the event block.
![image](https://user-images.githubusercontent.com/22294614/102057409-2825aa80-3dee-11eb-9599-3a8e3746e025.png)

2020-12-14 09:40 UTC, MarineDBL commented
> As we may expect events that can be much longer than usual events, here is the strategy that has been implemented to display the ToolTip for those types of events:
> 
> * up to 3 hours event: a standard tooltip is displayed with the lock icon and the message. No title. No Hours displayed.
>   ![image](https://user-images.githubusercontent.com/22294614/102057344-10e6bd00-3dee-11eb-80c3-8c05dde16934.png)
> * more than 3 hours. No tooltip displayed. The lock icon and the 'Confidential Mode' message is displayed within the event block.
>   ![image](https://user-images.githubusercontent.com/22294614/102057409-2825aa80-3dee-11eb-9599-3a8e3746e025.png)

Why is the lock green in the tooltip? Can we keep it black for design consistency?

2020-12-14 10:14 UTC, franck-fourel commented
> Why is the lock green in the tooltip? Can we keep it black for design consistency?

it's green because it was designed that way ;-) 
but we can have it black.

2020-12-14 10:51 UTC, MarineDBL commented
> > Why is the lock green in the tooltip? Can we keep it black for design consistency?
> 
> it's green because it was designed that way ;-)
> but we can have it black.

Yes; confirmed with Cyril. We can "paint it black"

2020-12-14 15:20 UTC, yvon-dblg commented on packages/viz/test/components/daily/ConfidentialTooltip.test.js
> + * Copyright (c) 2016, Tidepool Project
```suggestion
 * Copyright (c) 2020, Diabeloop
```

2020-12-14 15:20 UTC, yvon-dblg commented on packages/viz/src/components/daily/confidentialtooltip/ConfidentialTooltip.js
> + * Copyright (c) 2016, Tidepool Project
```suggestion
 * Copyright (c) 2020, Diabeloop
```

2020-12-14 15:30 UTC, yvon-dblg requested changes
Work as expected 😃 
Few comments though:
- Remove unuse image files like 
  - packages/tideline/img/lock.png
  -  packages/viz/src/images/lock.png
- Green tooltip icon
- Missing changelog

2020-12-14 15:30 UTC, yvon-dblg commented on packages/viz/src/components/daily/confidentialtooltip/ConfidentialTooltip.js
> + * Copyright (c) 2016, Tidepool Project
```suggestion
 * Copyright (c) 2020, Diabeloop
```

2020-12-14 15:30 UTC, yvon-dblg commented on packages/viz/test/components/daily/ConfidentialTooltip.test.js
> + * Copyright (c) 2016, Tidepool Project
```suggestion
 * Copyright (c) 2020, Diabeloop
```

2020-12-14 15:30 UTC, yvon-dblg commented on packages/viz/src/components/daily/confidentialtooltip/ConfidentialTooltip.js
> +class ConfidentialTooltip extends React.Component {
Could have been a function, but acceptable as a class.

2020-12-14 15:30 UTC, yvon-dblg commented on packages/viz/src/components/daily/confidentialtooltip/ConfidentialTooltip.css
> + * Copyright (c) 2016, Tidepool Project
```suggestion
 * Copyright (c) 2020, Diabeloop
```

2020-12-14 15:30 UTC, yvon-dblg commented on packages/tideline/package.json
> +    "@material-ui/icons": "^4.9.1"
```suggestion
    "sundial": "file:../sundial"
```
Not useful anymore

2020-12-14 15:30 UTC, yvon-dblg commented on packages/tideline/js/plot/confidentialModeEvent.js
> + * Copyright (c) 2014, Tidepool Project
```suggestion
 * Copyright (c) 2020, Diabeloop
```

2020-12-14 15:30 UTC, yvon-dblg commented on packages/tideline/js/plot/confidentialModeEvent.js
> +  const MaxSizeWithTooltip = 1000 * 60 * 60 * 3;
```suggestion
  const maxSizeWithTooltip = 1000 * 60 * 60 * 3;
```

2020-12-14 15:30 UTC, yvon-dblg commented on packages/tideline/js/plot/confidentialModeEvent.js
> +  const displayTooltip = (d) => (utils.getDuration(d).duration < MaxSizeWithTooltip);
```suggestion
  const displayTooltip = (d) => (utils.getDuration(d).duration < maxSizeWithTooltip);
```

2020-12-14 15:30 UTC, yvon-dblg commented on packages/tideline/js/plot/confidentialModeEvent.js
> +        if ( duration < MaxSizeWithTooltip) {
```suggestion
        if ( duration < maxSizeWithTooltip) {
```

2020-12-14 15:32 UTC, yvon-dblg commented on packages/viz/src/components/daily/confidentialtooltip/ConfidentialTooltip.js
> +      <Grid item> {t('Confidential Mode')} </Grid>
```suggestion
      <Grid item>{t('Confidential Mode')}</Grid>
```

2020-12-15 10:29 UTC, yvon-dblg approved these changes
LGTM

2020-12-15 10:29 UTC, merged