Rework & cleanup hooks
mdblp/blip pull request #402
Opened 2021-02-16 14:37 UTC by yvon-dblg

* Fix lost commit in rebase: Add coverage report
* Remove the ApiClient class
* Update auth hook
* Create team hook
* Create data hook
* Update related codes
* Fix tests

Sorry it's a big pull request. But all this code needs a clean-up.

2021-02-18 13:50 UTC, franck-fourel requested changes
Covering Bug detailed in YLP-454, it has to be added in the changelog.

packages/yourloops/pages/hcp/team-members-table.tsx, line 219: team-members-admin has to be replaced with team-member-admin 

couple of comments: 
- updating a member role in the team page is refreshing the page. It means that you are loosing the focus on the team you edited
-  getting the error `Failed to display teams: Cannot read property 'members' of undefined` when removing myself from a team

I have to say that I did not review all the details.

2021-02-22 14:31 UTC, yvon-dblg commented on packages/yourloops/models/shoreline.ts
> +  readonly emailVerified?: boolean;
Ideally, when all the api will be wired, all the fields will be readonly I think.

2021-02-24 14:04 UTC, franck-fourel requested changes
Apart from 1 missing translation (`modal-team-add-title` vs `team-modal-add-title`), it works fine.

2021-02-24 14:21 UTC, franck-fourel approved these changes

2021-02-24 15:03 UTC, merged