useSnackbar hook
mdblp/blip pull request #407
Opened 2021-02-17 09:57 UTC by leovalette

The aim of this hook is to handle concurrency display of snackbars and to make the Snackbars easier to use. Here you just need to call the hook which returns 2 things :

- openSnackbar : a method to open a snackbar, call it with the message you want to display and its severity
- snackbarParams : the paramaters you'll need to give to the Snackbar component

2021-02-25 14:20 UTC, Nas84 requested changes

2021-02-25 14:20 UTC, Nas84 commented on packages/yourloops/pages/profile/profile.tsx
> +      <Snackbar snackbarParams={snackbarParams} />
Could you rename the first snackbarParams to params ?

2021-02-25 14:20 UTC, Nas84 commented on packages/yourloops/components/utils/snackbar.tsx
> +      if (reason === "clickaway") {
a comment here to explain why we need test the reason can be usefull

2021-02-25 15:06 UTC, Nas84 approved these changes
LGTM

2021-02-26 14:18 UTC, yvon-dblg reviewed
Not sure: But maybe for the already implemented snackbar (I'm thinking of the one in pages/hcp), you could use your hook ?

2021-03-01 08:42 UTC, merged