Fix blip notes
mdblp/blip pull request #408
Opened 2021-02-17 17:52 UTC by yvon-dblg

2021-03-02 15:21 UTC, franck-fourel requested changes
The new note icon does not create a new note. Here is the message in the console
![image](https://user-images.githubusercontent.com/22294614/109670282-3ffe0680-7b73-11eb-9950-bf871a97663c.png)

2021-03-02 15:53 UTC, franck-fourel commented
I also got a Logout in the middle of a session
here is a screenshot of what I got. I was still able to navigate but I was not able to get patient data
![image](https://user-images.githubusercontent.com/22294614/109675097-c288c500-7b77-11eb-8ada-067f8d765305.png)

2021-03-02 17:48 UTC, yvon-dblg commented
> 
> 
> The new note icon does not create a new note. Here is the message in the console

Fixed in https://github.com/mdblp/blip/pull/427

2021-03-02 17:50 UTC, yvon-dblg commented
> 
> 
> I also got a Logout in the middle of a session
> here is a screenshot of what I got. I was still able to navigate but I was not able to get patient data

It was another problem: The server config was not right

But you have a point, we need to manage this situation
I will propose a PR for that later

2021-03-03 16:19 UTC, franck-fourel approved these changes
LGTM

PR https://github.com/mdblp/blip/pull/427 will fix the found issue.

2021-03-03 16:20 UTC, merged

2021-03-03 18:09 UTC, franck-fourel commented on packages/tideline/js/tidelinedata.js
> +  }
@yvon-dblg 
This has to be fixed in later version. 
If we have no settings (I know that should not happen) the default pump manufacturer is not added to the deviceEvents. At the end the reservoir  tooltip is broken.