Enable https connection on blip server
mdblp/blip pull request #410
Opened 2021-02-19 14:59 UTC by ragedblp

2021-02-19 15:47 UTC, ragedblp commented
Waiting for review

2021-02-22 13:24 UTC, yvon-dblg approved these changes
LGTM
But if you want to have a docker image, you need to bump version to an rc.

2021-02-23 08:19 UTC, yvon-dblg requested changes
package-lock.json need to be fully updated:
- `npm run mrproper`
- `rm package-lock.json`
- `npm install`

2021-02-23 08:19 UTC, yvon-dblg commented on packages/viz/package.json
> +    "gsap": "3.6.0",
```suggestion
    "gsap": "^3.6.0",
```

2021-02-23 10:28 UTC, yvon-dblg approved these changes
LGTM

2021-02-23 10:28 UTC, merged