YLP-514 Notifications screen
mdblp/blip pull request #418
Opened 2021-02-24 13:56 UTC by leovalette

This PR only implements the UI
Mocked will be removed in [YLP-461](https://diabeloop.atlassian.net/browse/YLP-461) or [YLP-465](https://diabeloop.atlassian.net/browse/YLP-465)

2021-02-25 15:21 UTC, Nas84 requested changes

2021-02-25 15:21 UTC, Nas84 commented on packages/yourloops/pages/notifications/notifications.tsx
> +              <Notification notification={notification} userRole={user?.roles && user.roles[0]} />
i would propose to split the notification props in order to remove the duplication.

2021-02-25 15:30 UTC, leovalette commented on packages/yourloops/pages/notifications/notifications.tsx
> +/**
notifications-list sounds good to me

2021-02-25 17:09 UTC, Nas84 approved these changes
lgtm

2021-03-03 11:08 UTC, franck-fourel requested changes
A small change requested
Wondering as well if we wanted to have something highlighting the fact that a notification was waiting for an action: the red circle on top of the bell ?

2021-03-03 13:53 UTC, closed without merging