YLP-443 DBL settings labels
mdblp/blip pull request #477
Opened 2021-04-15 15:15 UTC by franck-fourel

2021-04-15 16:08 UTC, franck-fourel commented
still need to validate https://github.com/mdblp/translations/pull/7 before merging this one

2021-04-16 13:15 UTC, yvon-dblg requested changes
Lint !
No it's not chocolate !

2021-04-16 13:15 UTC, yvon-dblg commented on packages/viz/src/components/settings/common/Table.js
> +        console.log(column);
```suggestion
```

2021-04-16 13:15 UTC, yvon-dblg commented on packages/viz/src/components/settings/common/Table.js
> +        return <td key={column.key} className={classname}>{column.cell(rowData, column.key)}</td>
```suggestion
        return <td key={column.key} className={classname}>{column.cell(rowData, column.key)}</td>;
```

2021-04-16 13:15 UTC, yvon-dblg commented on packages/viz/src/components/settings/common/Table.js
> +        if (column.className){
```suggestion
        if (column.className) {
```

2021-04-16 13:15 UTC, yvon-dblg commented on packages/viz/src/components/settings/Diabeloop.js
> +        main: `${t('Advanced')}`,
```suggestion
        main: level === 1 ? '' : `${t('Advanced')}`,
```

2021-04-16 13:15 UTC, yvon-dblg commented on packages/viz/src/components/settings/Diabeloop.js
> +    }
```suggestion
```

2021-04-16 13:15 UTC, yvon-dblg commented on packages/viz/src/components/settings/common/Table.js
> +        const classname = (column.className)? `styles.secondaryLabelWithMain` : "styles.secondaryLabelWithMain";
```suggestion
        const classname = (column.className) ? `styles.secondaryLabelWithMain` : "styles.secondaryLabelWithMain";
```

2021-04-19 16:53 UTC, yvon-dblg approved these changes
LGTM

2021-04-19 17:16 UTC, merged