YLP-684 URL Mapping
mdblp/blip pull request #479
Opened 2021-04-16 16:25 UTC by yvon-dblg

2021-05-03 16:45 UTC, franck-fourel requested changes
works fine but still a couple of comments

I noticed that the link to the profile modal does not work when clicking it from the Settings page 
![image](https://user-images.githubusercontent.com/22294614/116904899-986a8680-ac3e-11eb-99f3-07a20b700593.png)

The `/hcp/ path is still used in `getPatientLink()` in /blip/app/components/chart/header.js

2021-05-03 16:45 UTC, franck-fourel commented on packages/yourloops/components/patient-data.tsx
> +  const prefixURL = authHook.user?.role === UserRoles.patient ? props.prefixURL : `${props.prefixURL}/${paramPatientId}`;
why don't we put as well the userid for patient

2021-05-04 06:34 UTC, yvon-dblg commented
> I noticed that the link to the profile modal does not work when clicking it from the Settings page

For some reason, it is apparently the wanted behavior. But I didn't find where it comes from.
I just recall asking Leo about that too.

> The `/hcp/ path is still used in `getPatientLink()` in /blip/app/components/chart/header.js
👍 I will fix it, but it will fully fixed in https://github.com/mdblp/blip/pull/489
Given the changes made in this PR it will be easier.

> why don't we put as well the userid for patient
My bad. I didn't read well the document.

2021-05-04 13:05 UTC, franck-fourel approved these changes
LGTM

2021-05-04 13:19 UTC, merged