YLP-1120 Overview tab rework
mdblp/blip pull request #704
Opened 2022-01-12 08:56 UTC by fatb38

2022-01-26 11:01 UTC, TimCanu approved these changes

2022-01-26 11:02 UTC, TimCanu requested changes
Should the changelog be updated?

2022-01-27 14:57 UTC, yvon-dblg requested changes
Missing changelog

2022-02-01 16:13 UTC, yvon-dblg approved these changes
LGTM

2022-02-01 16:13 UTC, merged