YLP-1410 New left navigation drawer
mdblp/blip pull request #782
Opened 2022-04-12 12:35 UTC by fatb38

2022-04-19 12:25 UTC, TimCanu requested changes

2022-04-20 22:41 UTC, fatb38 commented on packages/yourloops/components/layouts/dashboard-layout.tsx
> +  const onClickMainHeaderMenuIcon = (): void => setDrawerMiniVariant(!drawerMiniVariant);
I was wondering if HamburgerIcon could be the right naming, but if we change the icon to another ?

2022-04-21 06:43 UTC, TimCanu commented on packages/yourloops/components/layouts/dashboard-layout.tsx
> +  const onClickMainHeaderMenuIcon = (): void => setDrawerMiniVariant(!drawerMiniVariant);
I would say that it is unlikely as I don't remember ever seeing something else than an Hamburger icon. But it is still a possibility.
Maybe something like `onClickHeaderShrinkIcon`? If none of these choice satisfy you, you can keep aziz

2022-04-21 08:02 UTC, TimCanu commented on packages/yourloops/test/components/menus/main-drawer.test.tsx
> +  const defaultWidth = "240px";
as discussed, can be imported from the main drawer component

2022-04-21 14:35 UTC, TimCanu approved these changes

2022-04-22 07:52 UTC, merged