Ylp 1445 add alerts in patients table
mdblp/blip pull request #795
Opened 2022-05-02 11:53 UTC by TimCanu

2022-05-03 15:20 UTC, fatb38 requested changes

2022-05-03 15:20 UTC, fatb38 commented on packages/yourloops/pages/hcp/patients/table.tsx
> +                    } arrow>
better readability
```suggestion
                   <StyledTooltip
                    title={<Typography color="inherit">{t("time-out-of-range-target-tooltip")}</Typography>}
                    arrow
                  >
```

2022-05-03 15:20 UTC, fatb38 commented on packages/yourloops/pages/hcp/patients/table.tsx
> +                className={`${classes.tableCellHeader} ${classes.alertTimeTargetHeader} ${patientListCommonClasses.mediumCell}`}>
better readability
```suggestion
               <StyledTableCell
                id="patients-list-header-alert-time-target"
                className={`${classes.tableCellHeader} ${classes.alertTimeTargetHeader} ${patientListCommonClasses.mediumCell}`}
              >
```

2022-05-03 15:21 UTC, fatb38 requested changes

2022-05-03 15:21 UTC, fatb38 commented on packages/yourloops/pages/hcp/patients/table.tsx
>  export const StyledTableCell = styled(withTheme(TableCell))((props) => ({
could be moved to a styled component folder or something like this ?

2022-05-03 15:27 UTC, TimCanu commented on packages/yourloops/pages/hcp/patients/table.tsx
> +    whiteSpace: "pre-line",
check the tooltip you blind boi

2022-05-04 12:40 UTC, fatb38 approved these changes
LGTM

2022-05-04 13:05 UTC, merged