Feature/YLP-1544 dialog invite remote monitoring
mdblp/blip pull request #820
Opened 2022-05-18 08:36 UTC by TimCanu

2022-06-02 09:01 UTC, CedricPerotto requested changes

2022-06-02 14:01 UTC, fatb38 requested changes

2022-06-02 15:09 UTC, TimCanu commented on packages/yourloops/components/dialogs/remote-monitoring-invite.tsx
> +  const updatePrescriptionInfo = (prescriptionInformation: PrescriptionInfo) => {
ESLint: 'prescriptionInfo' is already declared in the upper scope on line 108 column 9.(no-shadow

2022-06-02 15:10 UTC, TimCanu commented on packages/yourloops/components/patient/patient-monitoring-prescription.tsx
> +  const month = t("month").toLowerCase();
It is used twice (line 98 and line 227)

2022-06-03 07:53 UTC, CedricPerotto approved these changes

2022-06-03 08:18 UTC, fatb38 approved these changes

2022-06-03 08:38 UTC, merged