Feature/ylp 1466 create alarm card
mdblp/blip pull request #827
Opened 2022-05-31 15:31 UTC by TimCanu

2022-06-03 16:25 UTC, CedricPerotto requested changes
Uncomplete review... just the unit conversion.

2022-06-03 16:25 UTC, CedricPerotto commented on packages/yourloops/lib/units/utils.tsx
> +export const MGDL_PER_MMOL = 18;
As described here (it should be the same rule in all DBL products):
https://docs.google.com/spreadsheets/d/1P7b41oHoV73t5OgXFe22vo1Wso38u9ixgk3v0O81nKY/edit#gid=620459482

```suggestion
export const MGDL_PER_MMOL = 18.01577;
```

2022-06-07 12:12 UTC, Nas84 requested changes

2022-06-07 12:12 UTC, Nas84 commented on packages/yourloops/components/alarm/alarms-content.tsx
>  export interface TeamAlarmsContentProps {
What do you think to rename as AlarmsContentConfigurationProps ?

2022-06-07 12:12 UTC, Nas84 commented on packages/yourloops/components/alarm/alarms-content.tsx
> +function AlarmsContent(props: TeamAlarmsContentProps): JSX.Element {
What do you think to rename as AlarmsContentConfiguration ?

2022-06-08 07:26 UTC, Nas84 approved these changes
LGTM

2022-06-08 08:10 UTC, CedricPerotto approved these changes

2022-06-08 08:11 UTC, merged