Configure a custom issuer for auth0
mdblp/blip pull request #873
Opened 2022-07-08 05:40 UTC by ydrisR

2022-07-08 07:57 UTC, TimCanu commented on packages/yourloops/pages/login/login.tsx
> +  console.log(error);
```suggestion
  if (error) {
    console.log(error);
  }
```

2022-07-08 14:30 UTC, fatb38 requested changes

2022-07-08 14:30 UTC, fatb38 commented on packages/yourloops/pages/login/login.tsx
> +  console.log(error);
Agree to wrap it in a condition

2022-07-12 08:51 UTC, TimCanu approved these changes

2022-07-18 06:31 UTC, TimCanu approved these changes

2022-07-18 06:31 UTC, merged