Draft
mdblp/blip pull request #887
Opened 2022-08-18 13:18 UTC by TimCanu

2022-08-19 15:17 UTC, fatb38 commented
What do you think to regroup the utils files related to the UI (in integration tests) into a single file `UI-components` or something like this

2022-08-19 15:23 UTC, fatb38 approved these changes

2022-08-19 15:23 UTC, fatb38 commented on packages/yourloops/test/integration/utils/auth0.ts
> +      'http://your-loops.com/roles': ['hcp']
You can use the enum `UserMetadata` in models/user.ts
```suggestion
      [UserMetadata.Roles]: ['hcp']
```

2022-08-19 15:26 UTC, fatb38 requested changes
I saw remaining useless mock like in `main-drawer.test` with children property. These mocks could be removed !

2022-08-23 12:39 UTC, Nas84 requested changes
Seems that the jest config is duplicated, several solution exist to remove the duplication:
- leverage projects parameters
- shared a configuration module and import it

reference: [https://jestjs.io/docs/configuration#projects-arraystring--projectconfig](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig)

2022-08-24 13:48 UTC, Nas84 approved these changes
LGTM

2022-08-24 13:48 UTC, merged