Engineering/improve monorepo packages
mdblp/blip pull request #897
Opened 2022-09-08 08:49 UTC by fatb38

2022-09-12 08:09 UTC, Nas84 requested changes
Wonder if it is relevant to remove lerna. i am not convince

2022-09-14 13:43 UTC, TimCanu commented
@Nas84 I don't know much about lerna. What are the risks with this PR?

2022-09-28 08:32 UTC, TimCanu commented
As discussed with @Nas84 this PR is relevant :slightly_smiling_face:

2022-10-04 09:50 UTC, TimCanu approved these changes

2022-10-04 11:35 UTC, merged