engineering/added message error for input email and updated translate for email error message
mdblp/blip pull request #937
Opened 2022-10-24 11:22 UTC by Xwdrblue

…rror message

2022-10-24 15:30 UTC, fatb38 approved these changes
Don't forget to check system tests and if it's ok you can merge !

2022-10-27 13:42 UTC, fatb38 submitted a review, later dismissed

2022-10-28 11:04 UTC, TimCanu requested changes

2022-10-28 11:04 UTC, TimCanu commented on CHANGELOG.md
> +- YLP-1865 Add-an-error-message-if-email-is-not-valid-in-create-team-form
This is not correct :laughing:

2022-10-28 11:05 UTC, TimCanu commented on CHANGELOG.md
> +- YLP-1865 Add-an-error-message-if-email-is-not-valid-in-create-team-form
@fatb38 blind boi

2022-10-28 12:31 UTC, TimCanu approved these changes

2022-10-28 12:50 UTC, merged