YLP-1868 Add route to invite team member
mdblp/blip pull request #938
Opened 2022-10-24 15:22 UTC by TimCanu

2022-11-14 09:11 UTC, celia-rouis commented on packages/yourloops/lib/team/team-api.ts
> +    }
Some improvements could be done to this method:
- The error case could be handled first
- The HCP and patient case could be factorized

```ts
// To put at the top of the file to make sure these `const` never change
const HCP_ROUTE = 'hcps'
const PATIENTS_ROUTE = 'patients'

// ...
static getTeamsApiUrl(user: User): string {
  if (!user.isUserHcp() && !user.isUserPatient() {
    throw Error('...')
  }
  const userRoute = user.isUserHcp() ? HCP_ROUTE : PATIENT_ROUTE
  return `/bff/v1/${userRoute}/${user.id}/teams`
}

```

2022-11-18 11:04 UTC, fatb38 requested changes

2022-11-18 12:35 UTC, TimCanu commented on packages/yourloops/components/team/member-row.tsx
> +    (teamMember.status === UserInvitationStatus.pending && !teamMember.invitationId) // This condition basically means that the logged in user did not invite the pending user
Yes if you did not invite him yourself

2022-11-18 12:38 UTC, TimCanu commented on packages/yourloops/lib/team/team-api.ts
> +      throw Error(`User with role ${user.role} cannot retrieve teams`)
It the same for all the Error('...') that we throw in the app (we have 35 of them). Don't you think that this is out of scope?

2022-11-18 12:45 UTC, TimCanu commented on packages/yourloops/test/unit/lib/notifications/api.test.tsx
> +          type: 'unknownType' as unknown as NotificationType
I don't know how

2022-11-18 13:00 UTC, TimCanu commented on packages/yourloops/lib/notifications/notification-api.ts
> +  static async cancelInvitation(notificationId: string, teamId?: string, inviteeEmail?: string): Promise<void> {
I checked the back. The route call can cancel any invite. It searches an invite in the db (based on the id given) but you must have to give either the teamId or the invitee email.
That is why, in the cases in which I have both, I prefer to give both :slightly_smiling_face:

2022-11-18 13:02 UTC, TimCanu commented on packages/yourloops/test/unit/common/utils.ts
Good catch :slightly_smiling_face:

2022-11-18 13:34 UTC, fatb38 commented on packages/yourloops/lib/team/team-api.ts
> +      throw Error(`User with role ${user.role} cannot retrieve teams`)
https://www.linkedin.com/posts/javascript-developer_activity-6995787749240811520-1jkq?utm_source=share&utm_medium=member_desktop

2022-11-18 13:40 UTC, fatb38 commented on packages/yourloops/test/unit/lib/notifications/api.test.tsx
> +          type: 'unknownType' as unknown as NotificationType
Ok, hard work I guess, maybe later in when refactoring Notifications.

2022-11-18 13:41 UTC, TimCanu commented on packages/yourloops/lib/team/team-api.ts
> +      throw Error(`User with role ${user.role} cannot retrieve teams`)
ahaha but there is no rock in my way in my case

2022-11-18 13:41 UTC, fatb38 commented on packages/yourloops/lib/notifications/notification-api.ts
> +  static async cancelInvitation(notificationId: string, teamId?: string, inviteeEmail?: string): Promise<void> {
Ok, it's clear now 😉

2022-11-18 14:48 UTC, TimCanu commented
Do not merge. I think that there is an issue with an E2E test

2022-11-21 07:21 UTC, merged