engineering/YLP-1906-Fix-training-modal-CSS
mdblp/blip pull request #962
Opened 2022-11-17 09:44 UTC by Xwdrblue

2022-11-17 09:57 UTC, TimCanu requested changes

2022-11-17 09:57 UTC, TimCanu commented on packages/yourloops/pages/training/training.tsx
> +      // [theme.breakpoints.down('sm')]: {
no

2022-11-17 13:36 UTC, fatb38 requested changes

2022-11-17 13:36 UTC, fatb38 commented on packages/yourloops/pages/training/training.tsx
> +      marginTop: theme.spacing(2)
`display flex` is not usefull here, you can remove it. Also you could add a little bit more margin top

2022-11-17 13:36 UTC, fatb38 commented on packages/yourloops/pages/training/training.tsx
> +      padding: theme.spacing(1)
could be removed

2022-11-18 17:06 UTC, fatb38 requested changes

2022-11-18 17:06 UTC, fatb38 commented on packages/yourloops/pages/training/training.tsx
>        justifyContent: 'space-around',
to remove, useless without `display: flex`
```suggestion
```

2022-11-21 08:58 UTC, fatb38 approved these changes

2022-11-21 09:11 UTC, merged